package org.example.dao;

import org.example.dataobject.ColumnDO;

public interface ColumnDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    int insert(ColumnDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    int insertSelective(ColumnDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    ColumnDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    int updateByPrimaryKeySelective(ColumnDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    int updateByPrimaryKey(ColumnDO record);
}