package org.example.dao;

import org.example.dataobject.CommodityDO;

public interface CommodityDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    int insert(CommodityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    int insertSelective(CommodityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    CommodityDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    int updateByPrimaryKeySelective(CommodityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    int updateByPrimaryKey(CommodityDO record);
}