package org.example.dataobject;

import java.math.BigDecimal;

public class CommodityDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.id
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.commodityId
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    private String commodityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.commodityName
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    private String commodityname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.commodityUrl
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    private String commodityurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.commodityDescription
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    private String commoditydescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.nowPrice
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    private BigDecimal nowprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.salesVolume
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    private Integer salesvolume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.commoditySize
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    private String commoditysize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.isSale
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    private Integer issale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.originalPrice
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    private BigDecimal originalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.column
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    private String column;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.columnID
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    private String columnid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.id
     *
     * @return the value of commodity.id
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.id
     *
     * @param id the value for commodity.id
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.commodityId
     *
     * @return the value of commodity.commodityId
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    public String getCommodityid() {
        return commodityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.commodityId
     *
     * @param commodityid the value for commodity.commodityId
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    public void setCommodityid(String commodityid) {
        this.commodityid = commodityid == null ? null : commodityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.commodityName
     *
     * @return the value of commodity.commodityName
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    public String getCommodityname() {
        return commodityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.commodityName
     *
     * @param commodityname the value for commodity.commodityName
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    public void setCommodityname(String commodityname) {
        this.commodityname = commodityname == null ? null : commodityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.commodityUrl
     *
     * @return the value of commodity.commodityUrl
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    public String getCommodityurl() {
        return commodityurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.commodityUrl
     *
     * @param commodityurl the value for commodity.commodityUrl
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    public void setCommodityurl(String commodityurl) {
        this.commodityurl = commodityurl == null ? null : commodityurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.commodityDescription
     *
     * @return the value of commodity.commodityDescription
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    public String getCommoditydescription() {
        return commoditydescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.commodityDescription
     *
     * @param commoditydescription the value for commodity.commodityDescription
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    public void setCommoditydescription(String commoditydescription) {
        this.commoditydescription = commoditydescription == null ? null : commoditydescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.nowPrice
     *
     * @return the value of commodity.nowPrice
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    public BigDecimal getNowprice() {
        return nowprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.nowPrice
     *
     * @param nowprice the value for commodity.nowPrice
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    public void setNowprice(BigDecimal nowprice) {
        this.nowprice = nowprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.salesVolume
     *
     * @return the value of commodity.salesVolume
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    public Integer getSalesvolume() {
        return salesvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.salesVolume
     *
     * @param salesvolume the value for commodity.salesVolume
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    public void setSalesvolume(Integer salesvolume) {
        this.salesvolume = salesvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.commoditySize
     *
     * @return the value of commodity.commoditySize
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    public String getCommoditysize() {
        return commoditysize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.commoditySize
     *
     * @param commoditysize the value for commodity.commoditySize
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    public void setCommoditysize(String commoditysize) {
        this.commoditysize = commoditysize == null ? null : commoditysize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.isSale
     *
     * @return the value of commodity.isSale
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    public Integer getIssale() {
        return issale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.isSale
     *
     * @param issale the value for commodity.isSale
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    public void setIssale(Integer issale) {
        this.issale = issale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.originalPrice
     *
     * @return the value of commodity.originalPrice
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    public BigDecimal getOriginalprice() {
        return originalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.originalPrice
     *
     * @param originalprice the value for commodity.originalPrice
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    public void setOriginalprice(BigDecimal originalprice) {
        this.originalprice = originalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.column
     *
     * @return the value of commodity.column
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    public String getColumn() {
        return column;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.column
     *
     * @param column the value for commodity.column
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    public void setColumn(String column) {
        this.column = column == null ? null : column.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.columnID
     *
     * @return the value of commodity.columnID
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    public String getColumnid() {
        return columnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.columnID
     *
     * @param columnid the value for commodity.columnID
     *
     * @mbg.generated Wed Mar 10 19:49:37 CST 2021
     */
    public void setColumnid(String columnid) {
        this.columnid = columnid == null ? null : columnid.trim();
    }
}